create table if not exists public.publicaciones (
  id bigint generated by default as identity primary key,
  titulo text not null,
  resumen text not null,
  contenido text default '',
  categoria text default 'Institucional',
  imagen_url text default '',
  enlace text default '',
  estado text default 'borrador',
  fecha date not null default current_date,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

alter table public.publicaciones enable row level security;

drop policy if exists "lectura_publica_publicadas" on public.publicaciones;
create policy "lectura_publica_publicadas"
on public.publicaciones
for select
using (estado = 'publicado');

insert into public.publicaciones (titulo, resumen, contenido, categoria, imagen_url, enlace, estado, fecha)
select
  'Sitio web institucional en etapa de prueba',
  'Iniciamos una versión preliminar del sitio web de Agrupación Nothofagus para validar estructura, contenidos y canales de contacto.',
  'Versión preliminar del sitio web institucional.',
  'Institucional',
  '',
  '#',
  'publicado',
  '2026-05-29'
where not exists (select 1 from public.publicaciones);
